// Placeholder Firebase configuration for CI ONLY (Phase 12).
//
// The real lib/firebase_options.dart is generated by the FlutterFire CLI
// and gitignored because it contains the project's API key, so a fresh
// checkout has no such file and `flutter analyze` / `flutter test` would
// fail to resolve the import. CI copies this stub into place first.
//
// These values are deliberately fake. They are never used to reach a real
// project: the CI jobs only analyze and run unit/widget tests, which never
// call Firebase.initializeApp (screens take injected services or loaders).
// Anything that DOES need real configuration - running the app, the demo
// CLI, the migration CLI - reads it from a developer's own local file or
// from environment variables.
//
// Do not copy this over a real local firebase_options.dart; the CI script
// only writes it when the file is absent.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder [FirebaseOptions] used only so the tree compiles in CI.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('CI placeholder: web is not configured.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'CI placeholder: only the Android entry exists, and it is fake.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'ci-placeholder-not-a-real-key',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'ci-placeholder-project',
    storageBucket: 'ci-placeholder-project.appspot.com',
  );
}
